### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by bondz**
Add [bower](http://www.bower.io) support.

### CODE REVIEW

**Comment by bondz** [comment]
A new release has to be made so bower can accept the new file structure.

**Comment by yapapaya** [comment]
@bondz There are a couple of other changes that we're testing. We'll release a 1.0 soon

**Comment by bondz** [comment]
Ok. I understand.

**Comment by yapapaya** [comment]
@bondz Just released 1.0

**Comment by bondz** [comment]
Awesome. You need to mark v1.0 as the latest [release](https://github.com/yapapaya/jquery-cloneya/releases). Bower is still tracking v0.9.5.

**Comment by yapapaya** [comment]
Oh yeah, I forgot that. Haven't *released* anything in a long while on GitHub! Thanks, done!

**Comment by bondz** [comment]
Sorry, buy v1.0 is not a valid [semver](http://semver.org/) tag. 

To install 1.0 now, one would have to do

```batchfile
bower install cloneya#1.0
```

The current 1.0 (attack of the clones) might need to be changed to v1.0.1 or v1.0.0.

**Comment by yapapaya** [comment]
Sorry, fixed that. Renamed the version to 1.0.0.

**Comment by bondz** [comment]
Great. Works as expected now. :+1:

**Pull request merged**
